---
- name: Prepare Ubuntu 22.04 nodes for kubeadm (IPv4 + DNS fix + pkgs.k8s.io, no gpg-dearmor)
  hosts: all
  become: true

  vars:
    k8s_minor: "v1.31"          # override in group_vars if needed
    disable_firewall: true      # override in group_vars if needed

    # DNS policy: define in group_vars, keep defaults generic here
    dns_servers:
      - "1.1.1.1"
      - "8.8.8.8"

    base_packages:
      - ca-certificates
      - curl
      - apt-transport-https
      - software-properties-common
      - bash-completion
      - chrony
      - rsyslog
      - jq
      - vim

    k8s_packages:
      - kubelet
      - kubeadm
      - kubectl

  handlers:
    - name: restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true

  tasks:
    - name: Start
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: starting node prep"

    - name: Force IPv4 for APT
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/99force-ipv4
        mode: "0644"
        content: |
          Acquire::ForceIPv4 "true";

    # DNS quick fix (note: systemd-resolved can overwrite /etc/resolv.conf on some setups)
    - name: Write DNS to /etc/resolv.conf (IPv4)
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        mode: "0644"
        content: |
          {% for ns in dns_servers %}
          nameserver {{ ns }}
          {% endfor %}
          options timeout:1 attempts:2 rotate

    - name: Check DNS resolves prod-cdn.packages.k8s.io
      ansible.builtin.shell: |
        set -e
        getent hosts prod-cdn.packages.k8s.io | head -n1
      args:
        executable: /bin/bash
      register: dns_test
      changed_when: false

    - name: DNS OK
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: resolved -> {{ dns_test.stdout }}"

    - name: apt update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ base_packages }}"
        state: present

    - name: Disable swap (now)
      ansible.builtin.command: swapoff -a
      changed_when: false

    - name: Disable swap permanently (fstab)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(\s*[^#\n]+\s+[^ \t]+\s+swap\s+[^#\n]*)$'
        replace: '# \1'

    - name: Load kernel modules
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Persist kernel modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        mode: "0644"
        content: |
          overlay
          br_netfilter

    - name: sysctl for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        mode: "0644"
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl
      ansible.builtin.command: sysctl --system
      changed_when: false

    - name: Disable UFW (optional)
      ansible.builtin.systemd:
        name: ufw
        state: stopped
        enabled: false
      when: disable_firewall

    - name: Install containerd
      ansible.builtin.apt:
        name: containerd
        state: present

    - name: Generate containerd config if missing
      ansible.builtin.shell: |
        set -euo pipefail
        mkdir -p /etc/containerd
        if [ ! -s /etc/containerd/config.toml ]; then
          containerd config default > /etc/containerd/config.toml
        fi
      args:
        executable: /bin/bash
      changed_when: false

    - name: Enable SystemdCgroup in containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
      notify: restart containerd

    - name: Enable and start containerd
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true

    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Release.key as ASCII keyring (.asc)
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_minor }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        timeout: 20
        force: true

    - name: Add Kubernetes repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: "0644"
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ k8s_minor }}/deb/ /

    - name: apt update after adding repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install kubelet/kubeadm/kubectl
      ansible.builtin.apt:
        name: "{{ k8s_packages }}"
        state: present

    - name: Hold kubelet/kubeadm/kubectl
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ k8s_packages }}"

    - name: Enable kubelet (will start properly after init/join)
      ansible.builtin.systemd:
        name: kubelet
        enabled: true

    - name: Enable chrony
      ansible.builtin.systemd:
        name: chrony
        state: started
        enabled: true

    - name: Enable rsyslog
      ansible.builtin.systemd:
        name: rsyslog
        state: started
        enabled: true

    - name: Install cri-tools (crictl)
      ansible.builtin.apt:
        name: cri-tools
        state: present

    - name: Configure crictl for containerd
      ansible.builtin.copy:
        dest: /etc/crictl.yaml
        mode: "0644"
        content: |
          runtime-endpoint: "unix:///run/containerd/containerd.sock"
          image-endpoint: "unix:///run/containerd/containerd.sock"
          timeout: 0
          debug: false
          pull-image-on-create: false
          disable-pull-on-run: false

    - name: Done
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} ready: next kubeadm init (control-plane) / kubeadm join (workers)"